version: '3.3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    container_name: 'facebook'
    volumes:
      - .:/app
    ports:
      - 8002:8000
    depends_on:
      - redis
